from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class MotorProlog(Protocol):
    def nivel_riesgo_global(self, vivienda_id: str) -> str | None: ...

    def vulnerabilidad_estructural(self, vivienda_id: str) -> str | None: ...

    def vulnerabilidad_sanitaria(self, vivienda_id: str) -> str | None: ...

    def riesgo_electrico(self, vivienda_id: str) -> str | None: ...

    def riesgo_hidrologico(self, vivienda_id: str) -> str | None: ...

    def riesgo_epidemiologico(self, vivienda_id: str) -> str | None: ...

    def capacidad_resiliencia(self, vivienda_id: str) -> str | None: ...

    def recomendar(self, vivienda_id: str) -> list[str]: ...

    def limpiar_hechos(self, vivienda_id: str) -> None: ...

    def assert_hecho(self, vivienda_id: str, functor: str, valor: str) -> None: ...
